### ISSUE TITLE
[JOSS Review] Run tests / publish docs / scheduled run in workflow

### ISSUE THREAD

**Issue by mhubii** [ANP-Granular/ParticleTracking#84]
Again, please advise if wrong, are the tests run in the workflow https://github.com/ANP-Granular/ParticleTracking/blob/master/.github/workflows/ci.yml ? I can only find linting https://github.com/ANP-Granular/ParticleTracking/actions/runs/7207660157

Also, are the docs published on PR?

Please further consider a scheduled run, say weekly or similar, refer https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

**Comment by a-niem** [comment]
### Tests
> Again, please advise if wrong, are the tests run in the workflow https://github.com/ANP-Granular/ParticleTracking/blob/master/.github/workflows/ci.yml ? I can only find linting https://github.com/ANP-Granular/ParticleTracking/actions/runs/7207660157
> [...]
> Please further consider a scheduled run, say weekly or similar, refer https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

Currently, it is intended to only run linting in the mentioned workflow. This was decided because the tests take relatively long and on machines without a display require a proper setup of xvfb which has not been done yet.
We can add the running of tests to the workflow, as well as a time trigger.

### Docs
> Also, are the docs published on PR?

The respective versions of docs are automatically updated upon commits to the `master` and `develop` and when a new version tag is added.

**Comment by mhubii** [comment]
hm okay I see that this might be complicated, but I think running the tests via workflows would be necessary.

**Comment by mhubii** [comment]
https://github.com/openjournals/joss-reviews/issues/5986
